# AUTOMATICALLY generated header

# Generated from Import/Global/Services
Service_Serviced = 0x0          #  X  ; X  ; X  ; X  ; Terminates processing
Service_Static0E00 = 0x1        #  X  ; X  ; X  ;    ; Claim space at &E00
Service_Dynamic0E00 = 0x2       #  X  ; X  ; X  ;    ; Dynamic space above &E00
Service_AutoBoot = 0x3          #  X  ; X  ; X  ;    ; Cause filing system to boot
Service_UKCommand = 0x4         #  X  ; X  ; X  ; X  ; Do you know what this is??
Service_UnknownIRQ = 0x5        #  X  ; X  ; X  ;    ; Process IRQ
Service_Error = 0x6             #  X  ; X  ; X  ; X  ; A 'BRK' has occured, use ErrorV on Archimedes
Service_UKByte = 0x7            #  X  ; X  ; X  ; X  ; Unknown OSBYTEs go thru here
Service_UKWord = 0x8            #  X  ; X  ; X  ; X  ; Unknown OSWORDs go thru here
Service_Help = 0x9              #  X  ; X  ; X  ; X  ; Issued at the start of the *Help
Service_Claim0E00 = 0xa         #  X  ; X  ; X  ;    ; Claim the use of space at &E00
Service_ReleaseFIQ = 0xb        #  X  ; X  ; X  ; X  ;
Service_ClaimFIQ = 0xc          #  X  ; X  ; X  ; X  ; May only be issued from foreground !
Service_StartROMFS = 0xd        #  X  ; X  ; X  ;    ; Initialise ROM filing system
Service_ROMFSGetByte = 0xe      #  X  ; X  ; X  ;    ; ROM filing system get byte
Service_ClaimFSVectors = 0xf    #  X  ; X  ; X  ;    ; A new FS has claimed the vectors
Service_CloseSpoolExec = 0x10    #  X  ; X  ; X  ;    ; Closeure warning for Spool/Exec files
Service_Memory = 0x11            #  X  ; X  ; X  ; X  ; Font change, Memory movement
Service_StartUpFS = 0x12         #  X  ; X  ; X  ; X  ;
Service_RS423Char = 0x13         #     ; X  ;    ;    ; Character written to RS423 buffer
Service_PrinterChar = 0x14       #     ; X  ;    ;    ; Character written to printer buffer
Service_PollingInterupt = 0x15   #     ; X  ; X  ;    ; Offered every centi-second
Service_ExternalBell = 0x16      #     ; X  ;    ;    ; Offer the bell to external sound
Service_ExternalPurge = 0x17     #     ; X  ;    ;    ; Purge external sound buffers
Service_Post_Help = 0x18         #     ;    ; X  ; X  ; Passed round at the end of the *Help code
Service_StaticC000 = 0x21        #     ;    ; X  ;    ; Static space claim at &C000
Service_DynamicC000 = 0x22       #     ;    ; X  ;    ; Dynamic workspace claim, above &C000
Service_InformTopOfC000 = 0x23   #     ;    ; X  ;    ; Inform top of &C000 static space
Service_TestDynamicC000 = 0x24   #     ;    ; X  ;    ; Dynamic space test
Service_InformFilingSys = 0x25   #     ;    ; X  ;    ; Return filing system name, handles, and number
Service_ShutAllFiles = 0x26      #     ;    ; X  ;    ; Shut all files, in response to *Shut
Service_Reset = 0x27             #     ;    ; X  ; X  ;
Service_UKConfig = 0x28          #     ;    ; X  ; X  ;
Service_UKStatus = 0x29          #     ;    ; X  ; X  ;
Service_NewApplication = 0x2a    #     ;    ; X  ; X  ; Passed round before application/language is loaded/run
Service_DisplayBanner = 0x2b     #     ;    ; X  ;    ; Display startup banner
Service_CumanaBackup = 0x2c      #     ;    ; X  ;    ; Cumana removable cartidge drive
Service_BondIntKboard1 = 0x30    #     ;    ; X  ;    ; Indirected international keyboard service (Internat'nl PRB/COM)
Service_BondIntKboard2 = 0x31    #     ;    ; X  ;    ; Reserved for Paul Bond
Service_Tube = 0xfe              #  X  ; X  ; X  ; X  ; Means "Tube changing state"
Service_TubeMainInit = 0xff      #  X  ; X  ; X  ;    ;
Service_FSRedeclare = 0x40                       #  Add yourselves as Filing Systems again please
Service_Print = 0x41                             #  Printer Driver is being turned on/off (R2=0/1)
Service_LookupFileType = 0x42                    #  Do you know this file type ?
Service_International = 0x43                     #  Translate country/alphabet numbers/names or define set of chars
Service_KeyHandler = 0x44                        #  Offered when keyboard id ascertained
Service_PreReset = 0x45                          #  Offered after pressing the 'Break Key'
Service_ModeChange = 0x46                        #  Offered after a screen MODE change
Service_ClaimFIQinBackground = 0x47              #  Claim if you are FIQ owner and can release FIQ straight away.
Service_ReAllocatePorts = 0x48                   #  Econet is being started up again
Service_StartWimp = 0x49
Service_StartedWimp = 0x4a
Service_StartFiler = 0x4b
Service_StartedFiler = 0x4c
Service_PreModeChange = 0x4d                     #  Offered before mode changes, if claimed then returns if R0=0, else R0 -> error block
Service_MemoryMoved = 0x4e                       #  Offered at end of ChangeDynamic
Service_FilerDying = 0x4f
Service_ModeExtension = 0x50                     #  To allow soft modes
Service_ModeTranslation = 0x51                   #  For unknown monitor types
Service_MouseTrap = 0x52                         #  For non-click mouse warnings
Service_WimpCloseDown = 0x53                     #  for trapping Wimp_CloseDown calls
Service_Sound = 0x54                             #  Something's happening ... sub-rc's in Hdr.Sound
Service_NetFS = 0x55                             #  Either a *Logon or a *Bye has happened, or NetFS has started
Service_EconetDying = 0x56                       #  Econet is leaving Abandon all Tx/RxCBs
Service_WimpReportError = 0x57                   #  Wimp is opening/closing a ReportError window
Service_MIDI = 0x58                              #  MIDI is initialising or dying. Sub reason codes in Hdr.MIDI
Service_ResourceFSStarted = 0x59                 #  comes after ResourceFSStarting (for clients)
Service_ResourceFSDying = 0x5a                   #  when ResourceFS is killed / reloaded
Service_CalibrationChanged = 0x5b                #  when the calibration for the screen is changed
Service_WimpSaveDesktop = 0x5c                   #  when a save desktop to file is requested by the user
Service_WimpPalette = 0x5d                       #  on every Wimp_SetPalette
Service_MessageFileClosed = 0x5e                 #  from MessageTrans module
Service_NetFSDying = 0x5f                        #  NetFS is going to heaven, interceptors beware!
Service_ResourceFSStarting = 0x60                #  when ResourceFS is reloaded / reinited
Service_NFS = 0x61                               #  when NFS has mounted/dismounted or just loaded
Service_DBoxModuleDying = 0x62                   #  when the DBox module is rmkilled or succesfully tidied
Service_DBoxModuleStarting = 0x63                #  when the DBox module is rmloaded or reinitted
Service_TerritoryManagerLoaded = 0x64            #  when the territory manager is rmloaded or reinitted
Service_PDriverStarting = 0x65                   #  when the PDriver sharer module starts up
Service_PDumperStarting = 0x66                   #  when the PDumper module starts up
Service_PDumperDying = 0x67                      #  when the PDumper module dies
Service_CloseFile = 0x68                         #  when somebody wants to open a file (eg FileSwitch or PCEmulator)
Service_IdentifyDisc = 0x69                      #  when FileCore wants a disc format to be identified
Service_EnumerateFormats = 0x6a                  #  when ADFSFiler wants some format submenu entries
Service_IdentifyFormat = 0x6b                    #  when ADFS wishes to identify a format identifier from a *format command
Service_DisplayFormatHelp = 0x6c                 #  when ADFS wishes to display the list of available formats
Service_ValidateAddress = 0x6d                   #  when OS_ValidateAddress called with an apparently invalid address range
Service_FontsChanged = 0x6e                      #  when Font_ListFonts/Font_FindFont detects new Font$Path
Service_BufferStarting = 0x6f                    #  when Buffer manager installed (RMReinited, etc..).
Service_DeviceFSStarting = 0x70                  #  when devices to register with DeviceFS.
Service_DeviceFSDying = 0x71                     #  when DeviceFS is dying.
Service_SwitchingOutputToSprite = 0x72           #  when output switched to sprite or sprite mask or screen (inc. on mode change)
Service_PostInit = 0x73                          #  called after all modules have been initialised
Service_BASICHelp = 0x74                         #  called before printing BASIC help text ( r2 = Token).
Service_TerritoryStarted = 0x75                  #  called when a new territory is starting
Service_MonitorLeadTranslation = 0x76            #  to translate a monitor lead ID to a default monitortype, mode and sync
Service_SerialDevice = 0x77                      #  Passing of serial device handle (in r0) to all support module.
Service_PDriverGetMessages = 0x78                #  Get printer driver modules common Messages file info.
Service_DeviceDead = 0x79                        #  Device has been killed by DeviceFS, r0 =0, r2 =handle / =0 if all.
Service_ScreenBlanked = 0x7a                     #  Screen blanked by screen blanker.
Service_ScreenRestored = 0x7b                    #  Screen restored by screen blanker.
Service_DesktopWelcome = 0x7c                    #  Desktop about to start, display welcome message.
Service_DiscDismounted = 0x7d                    #  Disc has just been dismounted - close your viewers etc.
Service_ShutDown = 0x7e                          #  Switcher is shutting down.
Service_PDriverChanged = 0x7f                    #  PDriver has changed via PDriver_SelectDriver.
Service_ShutDownComplete = 0x80                  #  Switcher has completed the shutdown.
Service_DeviceFSCloseRequest = 0x81              #  Opening a device which already has maximum number of streams open
Service_InvalidateCache = 0x82                   #  ColourTrans has invalidated its cache
Service_ProtocolDying = 0x83                     #  Tells the world that a protocol is dying
Service_FindNetworkDriver = 0x84                 #  Issued when a protocol module is looking for device drivers
Service_WimpSpritesMoved = 0x85                  #  Window Managers sprite areas have moved.
Service_WimpRegisterFilters = 0x86               #  Window Manager has defaulted the filter owners.
Service_FilterManagerInstalled = 0x87            #  Please register with the Filter Manager now
Service_FilterManagerDying = 0x88                #  Filter Manager has just disappeared
Service_ModeChanging = 0x89                      #  Issued after Service_PreModeChange when a mode change is inevitable
Service_Portable = 0x8a                          #  Issued when various bits of power are removed or applied
Service_NetworkDriverStatus = 0x8b               #  Issued when various driver modules startup or die
Service_SyntaxError = 0x8c                       #  Issued by OS_CLI if syntax incorrect - for internationalisation
Service_EnumerateScreenModes = 0x8d              #  Enumerate which screen modes are available
Service_PagesUnsafe = 0x8e                       #  Physical memory pages are moving
Service_PagesSafe = 0x8f                         #  Physical memory pages have moved
Service_DynamicAreaCreate = 0x90                 #  Dynamic area just created
Service_DynamicAreaRemove = 0x91                 #  Dynamic area just removed
Service_DynamicAreaRenumber = 0x92               #  Dynamic area just renumbered
Service_ColourPickerLoaded = 0x93                #  when the colour picker is rmloaded or reinitted
Service_ModeFileChanged = 0x94                   #  when a new mode description file is loaded
Service_FreewayStarting = 0x95                   #  Freeway starting
Service_FreewayTerminating = 0x96                #  Freeway terminating
Service_ShareDStarting = 0x97                    #  ShareD starting
Service_ShareDTerminating = 0x98                 #  ShareD terminating
Service_ModulePostInitialisation = 0x99          #  Notification that a Module has just started
Service_ModulePreFinalisation = 0x9a             #  Notification that a Module is about to die
Service_EnumerateNetworkDrivers = 0x9b           #  Enumaration of network drivers
Service_PCMCIA = 0x9c                            #  PCMCIA system parts are starting and/or terminating
Service_DCIDriverStatus = 0x9d                   #  Issued when DCI 4 driver modules startup or die
Service_DCIFrameTypeFree = 0x9e                  #  Issued by DCI 4 driver modules when a frame type is relinquished
Service_DCIProtocolStatus = 0x9f                 #  Issued when DCI 4 protocol modules startup or die
Service_OmniAction = 0xa0                        #  Apollo service call from ANT Ltd.
Service_StatisticEnumerate = 0xa1                #  ANT Ltd.
Service_MbufManagerStatus = 0xa2                 #  ANT Ltd. / Acorn (DCI 4)
Service_SamplerSupport = 0xa3                    #  Jonathan Allin
Service_AccessLockKey = 0xa4                     #  Issued when 'Access Lock' key pressed on Stork
Service_RedrawManagerInstalled = 0xa5            #  ART kb
Service_RedrawManagerDying = 0xa6                #  ART kb
Service_URI = 0xa7                               #  ART rce
Service_NCDialUIStatus = 0xa8                    #  ANC ol
Service_ScreenBlanking = 0xa9                    #  ANC ol
Service_IRDirectorStarting = 0xaa                #  ANC cb
Service_CCWordSpell1 = 0xab                      #  Used by InterWord and SpellMaster
Service_CCWordSpell2 = 0xac                      #  Used by InterWord and SpellMaster
Service_Standby = 0xad                           #  ANC Steve Cormie
Service_NCAccessManager = 0xae                   #  ANC Ant Skelton
Service_CCWordSpell3 = 0xaf                      #  Used by InterWord and SpellMaster
Service_InternetStatus = 0xb0                    #  Issued by Internet module when address is configured
Service_Sleeping = 0xb1                          #  Online Media Set-Top Box
Service_TimeShare = 0xb2                         #  Alan Glover, Acorn, for SkyNet
Service_CDNewDrivePoll = 0xb3                    #  Timothy Roddis, Acorn, for CDFS
Service_Dialler = 0xb4                           #  ART Dialler
Service_UnknownPlatformFeature = 0xb5            #  ART WTurner
Service_CountATAPIDevices = 0xb6                 #  ART MChallis
Service_UKCompression = 0xb7                     #  ART WTurner
Service_CacheManager = 0xb8                      #  ART TRoddis
Service_ModulePreInit = 0xb9                     #  ART MStephens
Service_NCRegistry = 0xba                        #  ANC Ant Skelton
Service_SCTransportStarting = 0xbb               #  ANC Rich Buckley
Service_NCRegistrySupport = 0xbc                 #  ANC Ant Skelton
Service_MachineAddress = 0xbd                    #  ANC Steve Cormie
Service_CSFSStarting = 0xbe                      #  ANC Rich Buckley
Service_JavaStarting = 0xbf                      #  ANC Piers Wombwell
Service_PPPTimingOut = 0xc0                      #  ART Ben Laughton
Service_IRDirector = 0xc1                        #  Chris Berry
Service_IME = 0xc2                               #  Rich Buckley
Service_PCI = 0xc3                               #  William Turner
Service_Diallerb = 0xc4                          #  Ben Laughton
Service_ManagedAccess = 0xc5                     #  Ant Skelton
Service_MIDIMgr = 0xc6                           #  Tim Roddis
Service_MPEGControlStarting = 0xc7               #  Tim Dobson
Service_TaskPageOut = 0xcc                       #  RISCOS Ltd
Service_TaskPageIn = 0xcd                        #  RISCOS Ltd
Service_TaskSwapRequest = 0xce                   #  RISCOS Ltd
Service_OSInitBanner = 0xcf                      #  Justin Fletcher
Service_SoundControl = 0xd0                      #  Justin Fletcher
Service_HelpQuery = 0xd6                         #  Justin Fletcher
Service_ShutDownDismounting = 0xd7               #  Justin Fletcher
Service_ModuleStatus = 0xd8                      #  Justin Fletcher
Service_ModulePostInit = 0xda                    #  Castle [do not use; ModuleStatus provides more reliable info]
Service_ModulePostFinal = 0xdb                   #  Castle [do not use; ModuleStatus provides more reliable info]
Service_APCSBacktrace = 0xdc                     #  Justin Fletcher
Service_RTCSynchronised = 0xdd                   #  Justin Fletcher
Service_DisplayChanged = 0xde                    #  Justin Fletcher
Service_DisplayStatus = 0xdf                     #  Justin Fletcher
Service_NVRAM = 0xe0                             #  Steve Cormie
Service_SpriteReregister = 0xe1                  #  Justin Fletcher
Service_DeviceReregister = 0xe2                  #  Justin Fletcher
Service_PDriverGetSharedMessagesFile = 0x78
Service_ADFSPodule = 0x10800                #  &10800 locates ST506 podule
Service_ADFSPoduleIDE = 0x10801             #  &10801 locates IDE podule
Service_ADFSPoduleIDEDying = 0x10802        #  &10802 tells ADFS podule is dying
Service_ErrorStarting = 0x400c0             #  new wimp error extension system
Service_ErrorButtonPressed = 0x400c1
Service_ErrorEnding = 0x400c2
Service_WimpToolSpritesMoved = 0x400c3      #  tool sprites area changed
Service_CM_State_PreSleep = 0x40100
Service_CM_State_PostWake = 0x40101
Service_NetPrintCheckD1 = 0x40200           #  Used to find the SJ printer server
Service_Internet = 0x41200                  #  &41200 tells the world that Internet is dying
Service_FindProtocols = 0x41580             #  &41580    Called to find which protocols are available
Service_FindProtocolsEnd = 0x41581          #  &41581    Called when all protocols have been found.
Service_ProtocolNameToNumber = 0x41582      #  &41582    Called to convert a protocol name to its SWI base.
Service_TaskManagerAcknowledgements = 0x42680   #  &42680    Called to look (or give) for acknowledgement messages
Service_ToolboxSubMenu = 0x44ec0            #  &44EC0
Service_ToolboxStarting = 0x44ec1           #  &44EC1
Service_ToolboxTaskBorn = 0x44ec2           #  &44EC2
Service_ToolboxTaskDied = 0x44ec3           #  &44EC3
Service_ToolboxDying = 0x44ec4              #  &44EC4
Service_InetServices = 0x55640
Service_InternetVars = 0x80C41

# EOF
